### ISSUE TITLE
Checklist going live

### ISSUE THREAD

**Issue by freekmurze** [spatie/spatie.be#6]
## 1. Browserstack tests
- [x] Desktop: test on latest versions of Chrome, IE/Edge, Firefox, Safari
- [x] Mobile: test on latest versions of Mobile Safari, Android

### Assets
- [x] Search sources for `http://`. Replace by `https://`
- [x] Lint (s)css sources
- [x] Webfonts: is the live domain configured in services like Typekit, Fonts.com etc.?
- [x] Is the browserlist properly configured for autoprefixer and babel-preset-env?
- [x] When using PurgeCSS: check if layout is preserved.

### Scripts
- [x] Is `yarn.lock` present?
- [x] Check JS lint errors. Remove all `console.log` lines in scripts
- [x] Check for console errors

### Page weight
- [x] Evaluate total weight of at least homepage
- [x] Open Inspector network/timeline tab to identify heavy assets 
- [x] Check if heavy assets are cached 

### Performance
- [x] Use the Chrome DevTools and throttle your CPU and network with 10x CPU slowdown and set the network to "Good 3G".

## 3. Check content (with an open console)
- [x] Are all strings / images present (and translated)?
- [x] Does menu/submenu have a correct active state on every page?
- [x] Are 404, 500 and 503 pages provided? Do they provide useful content like 'back to home', search or a navigation tree?
- [x] Check all pages for n+1 problems

### Meta
- [x] Check page titles / descriptions
- [x] Test Facebook sharing. Provide og-tags if needed
- [x] Does Favicon load? Pin the tab in Safari to check pinned icon

_Repeat this section for all languages_

### Components
- [ ] Check structured data for news, events, products,... https://search.google.com/structured-data/testing-tool/

## 4. Server, DNS & Services
- [x] Install Let's Encrypt certificate
- [x] Check SSL certificate health https://www.ssllabs.com/ssltest/
- [x] Check your hostfile to make sure you're looking at the live site
- [x] Try visiting `www` domain, should redirect to `non-www`
- [x] Try out visiting `http`, should redirect to `https`
- [x] Verify that all http status codes are ok with https://github.com/spatie/http-status-check
- [x] Scan for mixed content with https://github.com/spatie/mixed-content-scanner-cli
- [ ] Verify that the content of robots header is current with `curl-I https://url` on `x-robots-tag`
- [ ] Remove development DNS record
- [x] Check dns propagation with https://www.whatsmydns.net/
- [x] Verify Tag Manager / Analytics have been correctly set up

### Google Search Console
- [x] Submit all www/non-www http/https variations
- [x] Set up non-www https as the preferred domain 
- [x] Crawl > Fetch as Google > Submit to index to kickstart index

### Server
- [ ] Are DigitalOcean backups enabled?
- [ ] Are Amazon backups enabled?
- [x] Is the output of artisan task `backup:run` ok?
- [x] Is artisan scheduled on Forge?
- [x] Is Horizon configured in Supervisor on Forge? Command should be `php artisan horizon`. Path should be `/home/forge/my-new-site.com/current`
- [x] Is the url being monitored by [Oh Dear!](https://ohdearapp.com/)?
- [ ] Is the server being monitored by our server-monitor?
